

import type { Product, Seller, Reel } from './types';

export const mockSellers: Seller[] = [
  {
    id: 'seller-1',
    name: 'Jaipur Jewels',
    craftswomanName: 'Meera Devi',
    background: 'Master Jeweler from a long line of royal artisans in Jaipur.',
    story: 'In the heart of the Pink City, where every lane echoes with tales of valor and royalty, Meera Devi carries a legacy passed down through seven generations. Her family, once jewelers to the maharajas, has honed the art of Kundan and Meenakari to perfection. "Every gemstone has a soul," Meera says, her hands deftly setting a stone. "I just help it sing its song. When you wear one of our pieces, you are not just wearing jewelry; you are wearing a piece of Jaipur\'s history, a story of timeless elegance passed from my ancestors to you."',
    logo: 'https://placehold.co/100x100.png',
    coverImage: 'https://placehold.co/1200x400.png',
    logoDataAiHint: 'kundan necklace',
    coverDataAiHint: 'jaipur fort'
  },
  {
    id: 'seller-2',
    name: 'Kutch Weaves',
    craftswomanName: 'Laxmi Ben',
    background: 'Leader of a women\'s weaving cooperative in the Rann of Kutch.',
    story: 'Laxmi Ben, with a smile as vibrant as the threads she weaves, leads a collective of over 50 women in a small village bordering the great Rann. For them, embroidery is more than an art; it is a language of survival and expression. "When I was a little girl, my mother taught me how to stitch my dreams into the fabric," she shares. "Today, we are stitching a future for our daughters. Each mirror, each thread in our work, reflects the harsh beauty of our desert home and the resilient spirit of its women."',
    logo: 'https://placehold.co/100x100.png',
    coverImage: 'https://placehold.co/1200x400.png',
    logoDataAiHint: 'embroidery pattern',
    coverDataAiHint: 'rann of kutch'
  },
  {
    id: 'seller-3',
    name: 'Bengal Terracotta',
    craftswomanName: 'Parvati Das',
    background: 'Third-generation terracotta artist from the riverbanks of Bengal.',
    story: 'From the fertile alluvial soil of the Ganges delta, Parvati Das molds clay into life. Her studio, a humble hut in the village of Panchmura, is a gallery of gods and goddesses, each with a story to tell. "The earth speaks to me," Parvati whispers, her hands covered in clay. "I am just a medium. When I work, I feel connected to my mother, and her mother before her, who all drew life from this same earth. These aren\'t just idols; they are blessings from our soil, shaped with love and prayer."',
    logo: 'https://placehold.co/100x100.png',
    coverImage: 'https://placehold.co/1200x400.png',
    logoDataAiHint: 'terracotta horse',
    coverDataAiHint: 'bengal village'
  },
  {
    id: 'seller-4',
    name: 'Mithila Paintings',
    craftswomanName: 'Sita Jha',
    background: 'Preserving the ancient art of Madhubani passed down through generations.',
    story: 'Sita Jha\'s fingers move with a rhythm that seems ancient, filling canvases with intricate lines and vibrant natural colors. In her village in the Mithila region, this art form is a sacred ritual, a visual prayer painted on the walls of homes. "My grandmother taught me that every line must be drawn with intention, every color filled with devotion," Sita explains. "We paint the stories of our gods, our folklore, our lives. To own a Madhubani painting is to bring home a piece of our collective soul, a celebration of life itself."',
    logo: 'https://placehold.co/100x100.png',
    coverImage: 'https://placehold.co/1200x400.png',
    logoDataAiHint: 'madhubani fish',
    coverDataAiHint: 'mithila village'
  },
   {
    id: 'seller-5',
    name: 'Kashmir Looms',
    craftswomanName: 'Fatima Ahmed',
    background: 'Pashmina weaver from a family of artisans in the Kashmir Valley.',
    story: 'High in the serene valleys of Kashmir, Fatima Ahmed continues a legacy of weaving that is as delicate as the mountain air. Her family has been crafting exquisite Pashmina shawls for centuries. "The wool is called \'soft gold\' for a reason," she says softly, her shuttle flying across the loom. "It takes immense patience and a gentle hand. Each shawl carries the warmth of our valley and the whispers of our stories. It is more than a garment; it is an embrace."',
    logo: 'https://placehold.co/100x100.png',
    coverImage: 'https://placehold.co/1200x400.png',
    logoDataAiHint: 'pashmina texture',
    coverDataAiHint: 'dal lake'
  },
  {
    id: 'seller-6',
    name: 'Channapatna Creations',
    craftswomanName: 'Suma Gowda',
    background: 'Toy-maker keeping the 200-year-old Channapatna craft alive.',
    story: 'In the \'town of toys,\' Suma Gowda turns soft ivory wood into glossy, colorful wonders. Using non-toxic vegetable dyes, she creates toys that are not just playful but safe and sustainable. "My grandfather used to say that every toy we make should bring a smile to a child\'s face," Suma recalls. "I carry that thought with me every day. We are not just making toys; we are crafting joy, creating safe and happy childhood memories, one colorful piece at a time."',
    logo: 'https://placehold.co/100x100.png',
    coverImage: 'https://placehold.co/1200x400.png',
    logoDataAiHint: 'wooden toy',
    coverDataAiHint: 'toy factory'
  },
  {
    id: 'seller-7',
    name: 'Kerala Mural Arts',
    craftswomanName: 'Anjali Varma',
    background: 'Reviving the divine art of Kerala temple murals.',
    story: 'Anjali Varma works in a quiet studio in Thrissur, surrounded by the rich scents of natural pigments. A scholar and artist, she has dedicated her life to Kerala mural painting, an art form traditionally found on temple walls. "These are not just paintings; they are visual scriptures," she explains. "Each color, each line, is prescribed by ancient texts. By bringing this art onto canvas, we are making it accessible to all, sharing the divine stories of our land with the world."',
    logo: 'https://placehold.co/100x100.png',
    coverImage: 'https://placehold.co/1200x400.png',
    logoDataAiHint: 'mural elephant',
    coverDataAiHint: 'kerala backwaters'
  },
  {
    id: 'seller-8',
    name: 'Rajasthani Leatherwork',
    craftswomanName: 'Bhanwari Devi',
    background: 'Expert in traditional Tilonia leather craft and embroidery.',
    story: 'Bhanwari Devi\'s hands, though weathered by time, move with practiced grace over pieces of leather. In her village near Ajmer, she leads a group of women who create beautifully embroidered leather goods. "Our craft is a gift from our ancestors," she says with pride. "We use locally sourced leather and stitch patterns that tell tales of the desert. Each journal, each bag, holds not just your belongings, but a piece of our resilient spirit."',
    logo: 'https://placehold.co/100x100.png',
    coverImage: 'https://placehold.co/1200x400.png',
    logoDataAiHint: 'leather mojari',
    coverDataAiHint: 'thar desert'
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Blue Pottery Vase',
    description: 'Handcrafted blue pottery vase from Jaipur, featuring traditional floral motifs. A perfect centerpiece to add a touch of Rajasthani elegance to your home.',
    price: 999,
    originalPrice: 1200,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'blue pottery',
    sellerId: 'seller-1',
    tags: ['home-decor', 'pottery', 'rajasthan'],
    culturalContext: 'Blue Pottery is a traditional craft of Jaipur, known for its vibrant cobalt blue dye. It was introduced by the Mughals and flourished under the patronage of the Jaipur royals in the 19th century.',
    sustainabilityCoins: 20,
    reviews: [
      { id: 'rev-1', author: 'Priya S.', rating: 5, comment: 'Absolutely beautiful! Looks even better in person.', date: '2023-05-15' },
      { id: 'rev-2', author: 'Amit K.', rating: 4, comment: 'Great quality and was packaged very securely. A bit smaller than I expected.', date: '2023-05-20' },
    ],
    stock: 15,
    sales: [
      { month: 'Jan', unitsSold: 25 },
      { month: 'Feb', unitsSold: 30 },
      { month: 'Mar', unitsSold: 45 },
      { month: 'Apr', unitsSold: 40 },
      { month: 'May', unitsSold: 50 },
      { month: 'Jun', unitsSold: 60 },
    ],
  },
  {
    id: 'prod-2',
    name: 'Hand-Embroidered Cushion Cover',
    description: 'Vibrant cushion cover with intricate Kutchi embroidery. Made with organic cotton and natural dyes, this piece adds a pop of color and traditional charm to any space.',
    price: 850,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'kutch embroidery',
    sellerId: 'seller-2',
    tags: ['textiles', 'embroidery', 'gujarat', 'home-decor'],
    culturalContext: 'Kutchi embroidery is a signature art form of the tribal communities of Kutch, Gujarat. The intricate motifs are inspired by nature and mythology, passed down through generations of women.',
    sustainabilityCoins: 15,
     reviews: [
      { id: 'rev-3', author: 'Meena V.', rating: 5, comment: 'The colors are so vibrant and the craftsmanship is outstanding. Highly recommend!', date: '2023-06-01' },
      { id: 'rev-4', author: 'Rajesh G.', rating: 5, comment: 'A perfect addition to our living room. It feels authentic and well-made.', date: '2023-06-05' },
    ],
    stock: 30,
    sales: [
      { month: 'Jan', unitsSold: 10 },
      { month: 'Feb', unitsSold: 15 },
      { month: 'Mar', unitsSold: 12 },
      { month: 'Apr', unitsSold: 20 },
      { month: 'May', unitsSold: 18 },
      { month: 'Jun', unitsSold: 25 },
    ],
  },
  {
    id: 'prod-3',
    name: 'Terracotta Ganesha Idol',
    description: 'Eco-friendly Ganesha idol handcrafted from river clay by artisans in Bengal. Ideal for worship or as a decorative piece, celebrating traditional terracotta art.',
    price: 500,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'ganesha idol',
    sellerId: 'seller-3',
    tags: ['terracotta', 'bengal', 'spiritual', 'home-decor'],
    sustainabilityCoins: 10,
    stock: 50,
    sales: [
      { month: 'Jan', unitsSold: 50 },
      { month: 'Feb', unitsSold: 40 },
      { month: 'Mar', unitsSold: 60 },
      { month: 'Apr', unitsSold: 80 },
      { month: 'May', unitsSold: 70 },
      { month: 'Jun', unitsSold: 90 },
    ],
  },
  {
    id: 'prod-4',
    name: 'Bandhani Silk Scarf',
    description: 'A luxurious silk scarf featuring the timeless Bandhani tie-dye technique from Gujarat. Lightweight and elegant, it is a versatile accessory for any occasion.',
    price: 2199,
    originalPrice: 2500,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'bandhani silk',
    sellerId: 'seller-2',
    tags: ['fashion', 'silk', 'bandhani', 'textiles'],
    sustainabilityCoins: 40,
    stock: 8,
    sales: [
      { month: 'Jan', unitsSold: 5 },
      { month: 'Feb', unitsSold: 8 },
      { month: 'Mar', unitsSold: 10 },
      { month: 'Apr', unitsSold: 7 },
      { month: 'May', unitsSold: 12 },
      { month: 'Jun', unitsSold: 15 },
    ],
  },
  {
    id: 'prod-5',
    name: 'Madhubani Painting',
    description: 'An intricate Madhubani painting depicting a traditional folk scene. Created with natural pigments on handmade paper, this art form originates from the Mithila region of Bihar.',
    price: 3500,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'madhubani painting',
    sellerId: 'seller-4',
    tags: ['art', 'painting', 'bihar', 'home-decor'],
    sustainabilityCoins: 50,
    stock: 5,
    sales: [
      { month: 'Jan', unitsSold: 2 },
      { month: 'Feb', unitsSold: 3 },
      { month: 'Mar', unitsSold: 1 },
      { month: 'Apr', unitsSold: 4 },
      { month: 'May', unitsSold: 3 },
      { month: 'Jun', unitsSold: 5 },
    ],
  },
   {
    id: 'prod-6',
    name: 'Rosewater Organic Lipstick',
    description: 'A creamy, hydrating lipstick made with organic rosewater and shea butter. This shade, "Jaipur Rose," offers a natural-looking flush perfect for daily wear.',
    price: 799,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'rose lipstick',
    sellerId: 'seller-1',
    tags: ['beauty', 'organic', 'lipstick'],
    culturalContext: 'Inspired by the royal gardens of Jaipur, this lipstick uses traditional ingredients known for their nourishing properties.',
    color: '#C73B7E',
    sustainabilityCoins: 10,
    stock: 25,
    sales: [
        { month: 'Jan', unitsSold: 20 },
        { month: 'Feb', unitsSold: 15 },
        { month: 'Mar', unitsSold: 30 },
        { month: 'Apr', unitsSold: 22 },
        { month: 'May', unitsSold: 40 },
        { month: 'Jun', unitsSold: 35 },
      ],
  },
  {
    id: 'prod-11',
    name: 'Ruby Red Lipstick',
    description: 'A bold, long-lasting lipstick in a classic ruby red. Enriched with Vitamin E, it provides a smooth, matte finish without drying your lips.',
    price: 899,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'red lipstick',
    sellerId: 'seller-1',
    tags: ['beauty', 'lipstick', 'makeup'],
    culturalContext: 'Red lipstick is a timeless symbol of confidence and glamour, worn for celebrations and special occasions across India.',
    color: '#9B111E',
    sustainabilityCoins: 10,
    stock: 50,
    sales: [
        { month: 'Jan', unitsSold: 18 },
        { month: 'Feb', unitsSold: 25 },
        { month: 'Mar', unitsSold: 20 },
        { month: 'Apr', unitsSold: 30 },
        { month: 'May', unitsSold: 28 },
        { month: 'Jun', unitsSold: 35 },
      ],
  },
  {
    id: 'prod-7',
    name: 'Wooden Kitchen Spoons',
    description: 'Set of 4 handcrafted wooden spoons, perfect for daily use. Made from sustainable neem wood, known for its antibacterial properties.',
    price: 399,
    originalPrice: 450,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'neem wood',
    sellerId: 'seller-3',
    tags: ['kitchen', 'woodwork', 'eco-friendly'],
    culturalContext: 'Neem wood is traditionally used in India for its health benefits. These spoons are a blend of utility and wellness.',
    sustainabilityCoins: 5,
    stock: 100,
    sales: [
      { month: 'Jan', unitsSold: 40 },
      { month: 'Feb', unitsSold: 60 },
      { month: 'Mar', unitsSold: 50 },
      { month: 'Apr', unitsSold: 75 },
      { month: 'May', unitsSold: 80 },
      { month: 'Jun', unitsSold: 90 },
    ],
  },
  {
    id: 'prod-8',
    name: 'Pattachitra Scroll Painting',
    description: 'A traditional Pattachitra scroll painting from Odisha, depicting a story from the Jagannath tradition. Painted on cloth with natural colors.',
    price: 4200,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'pattachitra painting',
    sellerId: 'seller-4',
    tags: ['art', 'pattachitra', 'odisha'],
    culturalContext: 'Pattachitra is a traditional, cloth-based scroll painting based in the eastern Indian states of Odisha and West Bengal.',
    sustainabilityCoins: 60,
    stock: 3,
    sales: [
      { month: 'Jan', unitsSold: 1 },
      { month: 'Feb', unitsSold: 0 },
      { month: 'Mar', unitsSold: 2 },
      { month: 'Apr', unitsSold: 1 },
      { month: 'May', unitsSold: 1 },
      { month: 'Jun', unitsSold: 2 },
    ],
  },
  {
    id: 'prod-9',
    name: 'Channapatna Wooden Toys',
    description: 'A colorful set of traditional Channapatna wooden toys, handcrafted in Karnataka. Made with vegetable dyes, they are safe for children and beautifully decorative.',
    price: 950,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'channapatna toys',
    sellerId: 'seller-6',
    tags: ['toys', 'channapatna', 'karnataka'],
    culturalContext: 'Channapatna toys are a particular form of wooden toys and dolls that are manufactured in the town of Channapatna in the Ramanagara district of Karnataka state, India.',
    sustainabilityCoins: 25,
    stock: 40,
    sales: [
      { month: 'Jan', unitsSold: 15 },
      { month: 'Feb', unitsSold: 20 },
      { month: 'Mar', unitsSold: 18 },
      { month: 'Apr', unitsSold: 25 },
      { month: 'May', unitsSold: 30 },
      { month: 'Jun', sold: 28 },
    ],
  },
  {
    id: 'prod-10',
    name: 'Pashmina Shawl',
    description: 'An exquisitely soft and warm Pashmina shawl from Kashmir. This timeless piece features delicate hand-embroidery, a hallmark of Kashmiri craftsmanship.',
    price: 15000,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'kashmiri shawl',
    sellerId: 'seller-5',
    tags: ['fashion', 'pashmina', 'kashmir', 'textiles'],
    sustainabilityCoins: 100,
    stock: 10,
    sales: [
      { month: 'Jan', unitsSold: 4 },
      { month: 'Feb', unitsSold: 2 },
      { month: 'Mar', unitsSold: 5 },
      { month: 'Apr', unitsSold: 3 },
      { month: 'May', unitsSold: 6 },
      { month: 'Jun', unitsSold: 4 },
    ],
  },
  {
    id: 'prod-12',
    name: 'Krishna Mural Canvas',
    description: 'A breathtaking Kerala mural painting on canvas depicting Lord Krishna. Made with traditional natural pigments, this artwork brings a divine and artistic touch to any room.',
    price: 7500,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'krishna mural',
    sellerId: 'seller-7',
    tags: ['art', 'painting', 'kerala', 'spiritual'],
    culturalContext: 'Kerala mural paintings are one of the oldest art forms in India, traditionally adorning temple walls and telling stories from Hindu mythology. They are known for their rich colors and distinct iconography.',
    sustainabilityCoins: 75,
    stock: 4,
    sales: [
      { month: 'Jan', unitsSold: 1 },
      { month: 'Feb', unitsSold: 1 },
      { month: 'Mar', unitsSold: 2 },
      { month: 'Apr', unitsSold: 0 },
      { month: 'May', unitsSold: 1 },
      { month: 'Jun', unitsSold: 2 },
    ],
  },
  {
    id: 'prod-13',
    name: 'Embroidered Leather Journal',
    description: 'A beautiful handmade leather journal with traditional Rajasthani embroidery. Perfect for writing, sketching, or as a unique gift.',
    price: 1200,
    image: 'https://placehold.co/300x300.png',
    dataAiHint: 'leather journal',
    sellerId: 'seller-8',
    tags: ['stationery', 'leather', 'rajasthan'],
    sustainabilityCoins: 25,
    stock: 20,
    sales: [
      { month: 'Jan', unitsSold: 8 },
      { month: 'Feb', unitsSold: 10 },
      { month: 'Mar', unitsSold: 12 },
      { month: 'Apr', unitsSold: 9 },
      { month: 'May', sold: 15 },
      { month: 'Jun', unitsSold: 11 },
    ],
  },
];

export const mockReels: Reel[] = [
  {
    id: 'reel-1',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-woman-making-a-pot-on-a-pottery-wheel-42226-small.mp4',
    caption: 'Unboxing our stunning new Blue Pottery collection! ✨ Which piece is your favorite? Let us know! #KalaConnect #HandmadeWithLove #JaipurCrafts',
    sellerId: 'seller-1',
    taggedProductIds: ['prod-1'],
  },
  {
    id: 'reel-2',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-working-on-a-loom-42238-small.mp4',
    caption: 'A glimpse into the magic of Kutch weaving. Every thread tells a story. #WomenInArt #KutchWeaves #SustainableFashion',
    sellerId: 'seller-2',
    taggedProductIds: ['prod-2', 'prod-4'],
  },
  {
    id: 'reel-3',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-artist-painting-on-a-canvas-42235-small.mp4',
    caption: 'Watch the magic of Madhubani unfold. Each stroke is a part of a larger story. #Artisan #IndianArt #Mithila',
    sellerId: 'seller-4',
    taggedProductIds: ['prod-5', 'prod-8'],
  },
  {
    id: 'reel-4',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-a-field-of-flowers-42228-small.mp4',
    caption: 'Feel the luxury, feel the tradition. Our new Bandhani scarves are here to brighten your day. #Handmade #Bandhani #SlowFashion',
    sellerId: 'seller-2',
    taggedProductIds: ['prod-4'],
  },
];
